export const SHOP_INFO = {
  name: "Nata Stok",
  tagline: "Сток одягу та взуття з Європи",
  source: "TikTok @natashumkiv",
  phone: "+38 050 57 56 811",
  phoneDigits: "+380505756811",
  viber: "+380505756811",
  telegram: "@natashumkiv",
  instagram: "natashumkiv",
  tiktok: "@natashumkiv",
  tiktokUrl: "https://www.tiktok.com/@natashumkiv",
  email: "info@natashum-stok.ua",
  city: "Україна",
  workHours: "Пн–Нд: 10:00–20:00",
  store: {
    city: "Івано-Франківськ",
    address: "вул. Гетьмана Івана Мазепи, 17",
    postal: "76010",
    hours: "Пн–Сб: 10:00–19:00, Нд: 11:00–17:00",
    lat: 48.9198976,
    lng: 24.7040745,
    mapQuery: "Івано-Франківськ, вул. Гетьмана Івана Мазепи, 17",
  },
  delivery: [
    "Нова Пошта — відправлення по всій Україні (1–2 робочі дні)",
    "Самовивіз — за домовленістю",
    "Укрпошта — за бажанням клієнта",
  ],
  payment: [
    "Повна передоплата на картку (Приват / Моно)",
    "Післяплата (накладений платіж Нової Пошти)",
    "Оплата за реквізитами ФОП для юридичних осіб",
  ],
};
