export const SHOP_INFO = {
  name: "Natasha Шум Сток",
  tagline: "Сток одягу та взуття з Європи",
  source: "TikTok @natashumkiv",
  phone: "+38 050 57 56 811",
  phoneDigits: "+380505756811",
  viber: "+380505756811",
  telegram: "@natashumkiv",
  instagram: "natashumkiv",
  tiktok: "@natashumkiv",
  tiktokUrl: "https://www.tiktok.com/@natashumkiv",
  email: "info@natashum-stok.ua",
  city: "Україна",
  workHours: "Пн–Нд: 10:00–20:00",
  delivery: [
    "Нова Пошта — відправлення по всій Україні (1–2 робочі дні)",
    "Самовивіз — за домовленістю",
    "Укрпошта — за бажанням клієнта",
  ],
  payment: [
    "Повна передоплата на картку (Приват / Моно)",
    "Післяплата (накладений платіж Нової Пошти)",
    "Оплата за реквізитами ФОП для юридичних осіб",
  ],
};
